default_job = "clippy"

[jobs]

[jobs.clippy]
command = ["cargo", "clippy", "--target", "wasm32-wasi", "--all-targets", "--all-features", "--color", "always"]
need_stdout = false
watch = ["build.rs", "tests", "benches", "examples"]
on_success = "quit"
