[package]
name = "sockets-client-tokio"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
tokio = { version = "1.40.0", features = ["macros", "rt", "net", "io-util"] }
